In [1]:
import numpy as np
import math

In [4]:
a = np.array([1, 2, 3])
print(a)
a.ndim

[1 2 3]


1

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

(2, 3)

In [8]:
b.shape


(2, 3)

In [9]:
a.dtype

dtype('int64')

In [10]:
d = np.zeros((2, 3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
e = np.ones((2, 3))
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
f = np.random.rand(2, 3)
f

array([[0.74123551, 0.86987156, 0.8669989 ],
       [0.74412513, 0.41348044, 0.81777751]])

In [13]:
g = np.arange(10, 50, 2)
g

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [14]:
h = np.linspace(0, 2, 10)
h

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])