## Indexing, Slicing and Iterating

In [3]:
import numpy as np

### Indexing

In [6]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a[2,0]

np.int64(5)

In [11]:
np.array([a[0,1], a[1,1], a[2,1]])

array([2, 4, 6])

### Boolean indexing

In [13]:
a[a > 5]

array([6])

### Slicing

In [14]:
a = np.array([10, 9, 8, 7, 6])
a[:3]

array([10,  9,  8])

In [15]:
a[2:4]

array([8, 7])

In [16]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
b[:2]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
b[:3, 3:]

array([[ 4],
       [ 8],
       [12]])

In [26]:
sub_array = b[:2, 1:3]
print(sub_array[0,0])

sub_array[0,0]=50
print(sub_array[0,0])
print(b)

50
50
[[ 1 50  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
