In [1]:
import numpy as np

In [4]:
wines = np.genfromtxt('DataOfModule1/winequality-red.csv', delimiter=';', skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [10]:
print(wines[:, 0:1])

[[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]


In [16]:
wines[:, [8,10,11]]

array([[ 3.51,  9.4 ,  5.  ],
       [ 3.2 ,  9.8 ,  5.  ],
       [ 3.26,  9.8 ,  5.  ],
       ...,
       [ 3.42, 11.  ,  6.  ],
       [ 3.57, 10.2 ,  5.  ],
       [ 3.39, 11.  ,  6.  ]])

In [19]:
print(sum(wines[:, [-1]]) / len(wines[:, [-1]]))


[5.63602251]


In [21]:
wines[:, [-1]].mean()

np.float64(5.6360225140712945)