# Array Operations

In [1]:
import numpy as np
import math

In [3]:
farenheit = np.array([0, -15, -5, -10, 0])

# °C = farenheit - 32 * 5 / 7 => °C

In [4]:
celcius = (farenheit - 32) * 5 / 7 
celcius

array([-22.85714286, -33.57142857, -26.42857143, -30.        ,
       -22.85714286])

In [14]:
celcius > -30

array([ True, False,  True, False,  True])

In [15]:
celcius % 2 == 0

array([False, False, False,  True, False])

In [28]:
A = np.array([[1, 1], [1, 1]])
B = np.array([[2, 0], [2, 1]])

# 2 2
# 0 2

# A*B
print(A@B)

[[4 1]
 [4 1]]


In [30]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array1.dtype


dtype('int64')

In [31]:
array2 = np.array([[3.3, 4.5, 5.1], [6.2, 7.6, 8.9]])
array2.dtype



dtype('float64')

In [38]:
array3 = array1+array2

print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

56.599999999999994
14.9
4.3
9.433333333333332
